# collections:
#   lps:
#     output: true
#     permalink: /:collection/:name
#   video:
#     output: true
#     permalink: /:collection/:name

url: "https://beachcity.com.au" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Values for the jekyll-archives gem
jekyll-archives:
  enabled: 'all'
  layout: 'blog-listing'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
    category: '/archives/tag/:name/'

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: BeachCity Media
author:
  name: BeachCity Media
  email:
  twitter: beachcity_life
social:
  name: BeachCity Media
  links:
    - beachcity.com.au
